const SERVER_PORT = 3001;
const SERVER_HOSTNAME = "127.0.0.1";
const MANIFEST_CHECK_INTERVAL_MS = 1000 * 60 * 60; //check once an hour
const MAX_ACTIVITIES_PAGE_LIMIT = 100;

const DB_PATH = process.env.DCLI_DB_PATH;
const MANIFEST_DB_PATH = process.env.MANIFEST_DB_PATH;
const MANIFEST_INFO_PATH = process.env.MANIFEST_INFO_PATH;

module.exports = {
    SERVER_PORT,
    SERVER_HOSTNAME,
    MANIFEST_CHECK_INTERVAL_MS,
    MAX_ACTIVITIES_PAGE_LIMIT,
    DB_PATH,
    MANIFEST_DB_PATH,
    MANIFEST_INFO_PATH
};