const FLOAT_DECIMAL_PRECISION = 2;
const DESTINY_API_KEY = process.env.REACT_APP_DESTINY_API_KEY;
const DATA_REFRESH_INTERVAL = 60 * 1000; //1  minute

export {
    FLOAT_DECIMAL_PRECISION,
    DESTINY_API_KEY,
    DATA_REFRESH_INTERVAL
};